
node.name: "testing"

path.data: "LOGSTASH_HOME/data"

pipeline.id: "main"
#pipeline.workers:
pipeline.batch.size: 125
pipeline.batch.delay: 50
pipeline.unsafe_shutdown: false
pipeline.ordered: auto

config.test_and_exit: false
config.reload.automatic: false
config.debug: false
config.support_escapes: false

http.enabled: true
http.host: 127.0.0.1
http.port: 9600
